---
title: '2020-04-15'
author: "楊于萱"
date: "2020/4/15"
output: html_document
---

```{r}
listExample
```

```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]] #拿出來
get1 <- listExample$`學期` #拿出來

get2 <- listExample["學期"] #只留下
```

```{r}
str(get1)
```

```{r}
str(get2)
```

### get1 取出
```{r}
get1$`108-1` -> get1_layer1; get1_layer1
str(get1_layer1)
```

```{r}
get1_layer1[[1]] -> get1_layer2; get1_layer2
str(get1_layer2)
```

```{r}
get1_layer2$teacher
```

```{r}
get1 <- listExample[["學期"]]
get1$`108-1` <- get1_layer1
get1_layer1[[1]] <- get1_layer2
get1_layer2$teacher

listExample[["學期"]]$`108-1`[[1]]$teacher
```

### get2 取出
```{r}
get2 <- listExample["學期"]
get2_layer1 <- get2[[1]] #get2$`學期`, get2[["學期"]]
get2_layer2 <- get2_layer1[["108-1"]]
get2_layer3 <- get2_layer2[[1]]
get2_layer3$teacher

listExample["學期"][["學期"]][["108-1"]][[1]]$teacher
```

#### list應用{-}

```{r}
vector1 <- c(a=1, b=3, c=4)
vector1[["a"]]
vector1[c("a","c")]
vector1$a #不能用

list1 <- list(a=1,b=3,c=4)
list1[["a"]]
list1[c("a","c")]
list1$a
```

今明兩日台北市、新北市氣溫:
```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]][[2]]
```


```{r}
today <- list(
  list("台北市",highest_temp=c(highest_temp = 25),
       lowest_temp=c(lowest_temp = 18)),
  list("新北市",highest_temp=c(highest_temp = 24),
       lowest_temp=c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]]$highest_temp
```

```{r}
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

str(weather)
```

## 新增/替換/刪除元素

**範例**
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```

```{r}
a[[7]] <- "Johnson"
a

a <- c(a, c("Mary"))
a
```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

#新增資料
list1[[2]] <- list(
  name="Mary", 
  birthday=ymd("1998-08-24")
)
str(list1)
```

```{r}
list1[[2]]$status <- c(height=163,weight=45)
list1[[1]]$status[[1]] <- 176
str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

108-1新增一個“產業經濟學”。

產業經濟學，同時加上教師Wen及成績88

```{r}
str(listExample)
```

```{r}
listExample$學期$`108-1`[[2]] <- list(
  name="產業經濟學", 
  teacher="Wen", 
  grade=88
)
str(listExample)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

刪除可以使用[- c(數字位置)]
```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```
刪除Jack的status.

刪除Mary的status, blookType.
```{r}
list1[[1]][-3] -> list1[[1]]
list1[[2]][-c(3, 5)] ->list1[[2]]
```